server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        # ТОВА Е ПРОМЯНАТА: Добавяме index.csr.html на първо място
        index index.csr.html index.html index.htm;

        # ТОВА СЪЩО СЕ СМЕНЯ: Пренасочваме непознатите пътища към вашия Angular HTML
        try_files $uri $uri/ /index.csr.html;
    }

    location /api/ {
        proxy_pass http://backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
