plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.ebrd'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Web & GraphQL
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-graphql'

    // DB & JPA  (PostgreSQL)
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'

    // flyway
    implementation 'org.flywaydb:flyway-core'
    implementation 'org.springframework.boot:spring-boot-starter-flyway'
    implementation 'org.flywaydb:flyway-database-postgresql'

    // Spring validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Security & JWT
    // JWT API signature interfaces
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'

    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'

    // JSON processing mapper extension (integrates directly with Spring Boot's Jackson)
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'


    //Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // mapper using mapstruct
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

    // Test
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.springframework.boot:spring-boot-starter-graphql'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation 'org.springframework.graphql:spring-graphql-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:testcontainers-postgresql:2.0.5'
    testImplementation 'org.springframework.boot:spring-boot-starter-jdbc'
    testImplementation 'org.springframework.graphql:spring-graphql-test'


    testImplementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    testRuntimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    testRuntimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

}

test {
    useJUnitPlatform()
}